server:
  port: 8080

spring:
  application:
    name: auth
  profiles:
    active: dev

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/**/*Mapper.xml
    - classpath*:/mapper/**/*Dao.xml
  type-aliases-package: com.wen.sso.auth.model
